name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: thumbv6m-none-eabi
            dir: neotron-bmc-pico/
          - target: thumbv7m-none-eabihf
            dir: neotron-bmc-nucleo/
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Add Target
      run: rustup target add ${{ matrix.target }}
    - name: Install flip-link
      run: cd / && cargo install flip-link
    - name: Build project
      run: cd ${{ matrix.dir }} && cargo build --release --verbose --target=${{ matrix.target }}
