on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Add Target
        run: rustup target add thumbv6m-none-eabi
      - name: Install flip-link
        run: cd / && cargo install flip-link
      - name: Build
        run: cargo build --release --target=thumbv6m-none-eabi
      - name: Get Branch Name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.branch_name.outputs.SOURCE_TAG }}
          draft: false
          prerelease: false
      - name: Upload files to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/thumbv6m-none-eabi/release/neotron-bmc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
